import { LeaderboardGame } from '@/types/roblox';

// Mock data for when Roblox API is unavailable
export const mockGames: LeaderboardGame[] = [
  {
    rank: 1,
    universeId: 2753915549,
    placeId: 6872265039,
    name: "Blox Fruits",
    description: "Welcome to Blox Fruits! Become a master swordsman or a powerful blox fruit user as you train to become the strongest player!",
    playerCount: 524789,
    totalUpVotes: 8234567,
    totalDownVotes: 245678,
    rating: 97,
    creatorName: "Gamer Robot Inc",
    creatorType: "Group",
    genre: "Adventure",
    thumbnailUrl: "https://tr.rbxcdn.com/180DAY-f6e9e8eb2e89458d9f0e3a8f3a0d8f3a/768/432/Image/Webp",
    iconUrl: "https://tr.rbxcdn.com/180DAY-f6e9e8eb2e89458d9f0e3a8f3a0d8f3a/150/150/Image/Webp",
    ageRecommendation: "9+",
    lastUpdated: new Date().toISOString(),
  },
  {
    rank: 2,
    universeId: 65241,
    placeId: 189707,
    name: "Adopt Me!",
    description: "🎄🎁 WINTER UPDATE! 🎁🎄 Adopt and raise adorable pets, decorate your house, and play with friends!",
    playerCount: 423156,
    totalUpVotes: 6123456,
    totalDownVotes: 312456,
    rating: 95,
    creatorName: "Uplift Games",
    creatorType: "Group",
    genre: "Town and City",
    thumbnailUrl: "https://tr.rbxcdn.com/180DAY-adoptme/768/432/Image/Webp",
    iconUrl: "https://tr.rbxcdn.com/180DAY-adoptme/150/150/Image/Webp",
    ageRecommendation: "All Ages",
    lastUpdated: new Date().toISOString(),
  },
  {
    rank: 3,
    universeId: 920587237,
    placeId: 2474168535,
    name: "Tower of Hell",
    description: "Race against time to climb the randomly generated tower! No checkpoints, one life!",
    playerCount: 312456,
    totalUpVotes: 4567890,
    totalDownVotes: 234567,
    rating: 95,
    creatorName: "YXCeptional Studios",
    creatorType: "Group",
    genre: "Obby",
    thumbnailUrl: "https://tr.rbxcdn.com/180DAY-towerofhell/768/432/Image/Webp",
    iconUrl: "https://tr.rbxcdn.com/180DAY-towerofhell/150/150/Image/Webp",
    ageRecommendation: "9+",
    lastUpdated: new Date().toISOString(),
  },
  {
    rank: 4,
    universeId: 3260590327,
    placeId: 8737899170,
    name: "Brookhaven 🏡RP",
    description: "Welcome to Brookhaven! Get a house, drive around the city, roleplay, and hang out with friends!",
    playerCount: 298456,
    totalUpVotes: 5234567,
    totalDownVotes: 345678,
    rating: 94,
    creatorName: "Wolfpaq",
    creatorType: "Group",
    genre: "Town and City",
    thumbnailUrl: "https://tr.rbxcdn.com/180DAY-brookhaven/768/432/Image/Webp",
    iconUrl: "https://tr.rbxcdn.com/180DAY-brookhaven/150/150/Image/Webp",
    ageRecommendation: "All Ages",
    lastUpdated: new Date().toISOString(),
  },
  {
    rank: 5,
    universeId: 1962086868,
    placeId: 5496189786,
    name: "Murder Mystery 2",
    description: "Classic murder mystery game! Can you survive? Will you solve the mystery?",
    playerCount: 245678,
    totalUpVotes: 4123456,
    totalDownVotes: 234567,
    rating: 94,
    creatorName: "Nikilis",
    creatorType: "User",
    genre: "Horror",
    thumbnailUrl: "https://tr.rbxcdn.com/180DAY-mm2/768/432/Image/Webp",
    iconUrl: "https://tr.rbxcdn.com/180DAY-mm2/150/150/Image/Webp",
    ageRecommendation: "9+",
    lastUpdated: new Date().toISOString(),
  },
  {
    rank: 6,
    universeId: 2788229376,
    placeId: 7449423635,
    name: "Pet Simulator X",
    description: "Collect coins, hatch eggs, and discover rare pets in this ultimate pet collecting game!",
    playerCount: 198765,
    totalUpVotes: 3456789,
    totalDownVotes: 198765,
    rating: 95,
    creatorName: "BIG Games",
    creatorType: "Group",
    genre: "All",
    thumbnailUrl: "https://tr.rbxcdn.com/180DAY-psx/768/432/Image/Webp",
    iconUrl: "https://tr.rbxcdn.com/180DAY-psx/150/150/Image/Webp",
    ageRecommendation: "All Ages",
    lastUpdated: new Date().toISOString(),
  },
  {
    rank: 7,
    universeId: 142823291,
    placeId: 286090429,
    name: "Arsenal",
    description: "Shoot your way through a variety of weapons in this fast-paced shooter!",
    playerCount: 187654,
    totalUpVotes: 4234567,
    totalDownVotes: 234567,
    rating: 95,
    creatorName: "ROLVe Community",
    creatorType: "Group",
    genre: "Shooter",
    thumbnailUrl: "https://tr.rbxcdn.com/180DAY-arsenal/768/432/Image/Webp",
    iconUrl: "https://tr.rbxcdn.com/180DAY-arsenal/150/150/Image/Webp",
    ageRecommendation: "9+",
    lastUpdated: new Date().toISOString(),
  },
  {
    rank: 8,
    universeId: 1537690962,
    placeId: 4117265786,
    name: "Bee Swarm Simulator",
    description: "Grow your swarm of bees, collect pollen, and make honey!",
    playerCount: 165432,
    totalUpVotes: 3567890,
    totalDownVotes: 178965,
    rating: 95,
    creatorName: "Onett",
    creatorType: "User",
    genre: "All",
    thumbnailUrl: "https://tr.rbxcdn.com/180DAY-beeswarm/768/432/Image/Webp",
    iconUrl: "https://tr.rbxcdn.com/180DAY-beeswarm/150/150/Image/Webp",
    ageRecommendation: "All Ages",
    lastUpdated: new Date().toISOString(),
  },
  {
    rank: 9,
    universeId: 2474168535,
    placeId: 6284583030,
    name: "Doors",
    description: "Explore a mysterious hotel filled with dangerous entities. How far can you go?",
    playerCount: 154321,
    totalUpVotes: 2987654,
    totalDownVotes: 156789,
    rating: 95,
    creatorName: "LSPLASH",
    creatorType: "Group",
    genre: "Horror",
    thumbnailUrl: "https://tr.rbxcdn.com/180DAY-doors/768/432/Image/Webp",
    iconUrl: "https://tr.rbxcdn.com/180DAY-doors/150/150/Image/Webp",
    ageRecommendation: "9+",
    lastUpdated: new Date().toISOString(),
  },
  {
    rank: 10,
    universeId: 3110594450,
    placeId: 8430374047,
    name: "Jailbreak",
    description: "Escape prison and live a life of crime, or join the police force and stop the criminals!",
    playerCount: 143210,
    totalUpVotes: 4567890,
    totalDownVotes: 345678,
    rating: 93,
    creatorName: "Badimo",
    creatorType: "Group",
    genre: "Adventure",
    thumbnailUrl: "https://tr.rbxcdn.com/180DAY-jailbreak/768/432/Image/Webp",
    iconUrl: "https://tr.rbxcdn.com/180DAY-jailbreak/150/150/Image/Webp",
    ageRecommendation: "9+",
    lastUpdated: new Date().toISOString(),
  },
  {
    rank: 11,
    universeId: 3759258620,
    placeId: 9887728264,
    name: "Natural Disaster Survival",
    description: "Survive various natural disasters on different maps!",
    playerCount: 132109,
    totalUpVotes: 2876543,
    totalDownVotes: 198765,
    rating: 94,
    creatorName: "Stickmasterluke",
    creatorType: "User",
    genre: "Survival",
    thumbnailUrl: "https://tr.rbxcdn.com/180DAY-nds/768/432/Image/Webp",
    iconUrl: "https://tr.rbxcdn.com/180DAY-nds/150/150/Image/Webp",
    ageRecommendation: "All Ages",
    lastUpdated: new Date().toISOString(),
  },
  {
    rank: 12,
    universeId: 2165221560,
    placeId: 5895193441,
    name: "Anime Fighters Simulator",
    description: "Fight through iconic anime worlds and collect powerful fighters!",
    playerCount: 121098,
    totalUpVotes: 2456789,
    totalDownVotes: 167890,
    rating: 94,
    creatorName: "Sulley",
    creatorType: "User",
    genre: "Fighting",
    thumbnailUrl: "https://tr.rbxcdn.com/180DAY-afs/768/432/Image/Webp",
    iconUrl: "https://tr.rbxcdn.com/180DAY-afs/150/150/Image/Webp",
    ageRecommendation: "9+",
    lastUpdated: new Date().toISOString(),
  },
  {
    rank: 13,
    universeId: 3897847441,
    placeId: 10221206147,
    name: "King Legacy",
    description: "Become a powerful pirate or marine in this One Piece inspired adventure!",
    playerCount: 109876,
    totalUpVotes: 2234567,
    totalDownVotes: 145678,
    rating: 94,
    creatorName: "Tier Games",
    creatorType: "Group",
    genre: "Adventure",
    thumbnailUrl: "https://tr.rbxcdn.com/180DAY-kinglegacy/768/432/Image/Webp",
    iconUrl: "https://tr.rbxcdn.com/180DAY-kinglegacy/150/150/Image/Webp",
    ageRecommendation: "9+",
    lastUpdated: new Date().toISOString(),
  },
  {
    rank: 14,
    universeId: 1234567890,
    placeId: 987654321,
    name: "Work at a Pizza Place",
    description: "The classic Roblox game! Work together to run a pizza place.",
    playerCount: 98765,
    totalUpVotes: 3456789,
    totalDownVotes: 234567,
    rating: 94,
    creatorName: "Dued1",
    creatorType: "User",
    genre: "Town and City",
    thumbnailUrl: "https://tr.rbxcdn.com/180DAY-pizza/768/432/Image/Webp",
    iconUrl: "https://tr.rbxcdn.com/180DAY-pizza/150/150/Image/Webp",
    ageRecommendation: "All Ages",
    lastUpdated: new Date().toISOString(),
  },
  {
    rank: 15,
    universeId: 2543673050,
    placeId: 6810928071,
    name: "Shindo Life",
    description: "Train to become a powerful ninja in this Naruto-inspired RPG!",
    playerCount: 87654,
    totalUpVotes: 2123456,
    totalDownVotes: 134567,
    rating: 94,
    creatorName: "RELL World",
    creatorType: "Group",
    genre: "Adventure",
    thumbnailUrl: "https://tr.rbxcdn.com/180DAY-shindo/768/432/Image/Webp",
    iconUrl: "https://tr.rbxcdn.com/180DAY-shindo/150/150/Image/Webp",
    ageRecommendation: "9+",
    lastUpdated: new Date().toISOString(),
  },
  {
    rank: 16,
    universeId: 2985361623,
    placeId: 7806232843,
    name: "Piggy",
    description: "Survive and escape from Piggy in this thrilling horror game!",
    playerCount: 76543,
    totalUpVotes: 1987654,
    totalDownVotes: 123456,
    rating: 94,
    creatorName: "MiniToon",
    creatorType: "User",
    genre: "Horror",
    thumbnailUrl: "https://tr.rbxcdn.com/180DAY-piggy/768/432/Image/Webp",
    iconUrl: "https://tr.rbxcdn.com/180DAY-piggy/150/150/Image/Webp",
    ageRecommendation: "9+",
    lastUpdated: new Date().toISOString(),
  },
  {
    rank: 17,
    universeId: 2611368381,
    placeId: 6943147143,
    name: "All Star Tower Defense",
    description: "Defend your base using characters from your favorite anime!",
    playerCount: 65432,
    totalUpVotes: 1876543,
    totalDownVotes: 112345,
    rating: 94,
    creatorName: "Top Down Games",
    creatorType: "Group",
    genre: "Strategy",
    thumbnailUrl: "https://tr.rbxcdn.com/180DAY-astd/768/432/Image/Webp",
    iconUrl: "https://tr.rbxcdn.com/180DAY-astd/150/150/Image/Webp",
    ageRecommendation: "9+",
    lastUpdated: new Date().toISOString(),
  },
  {
    rank: 18,
    universeId: 3527629274,
    placeId: 9285503047,
    name: "Untitled Tag Game",
    description: "Fast-paced tag game where you run, hide, and tag your friends!",
    playerCount: 54321,
    totalUpVotes: 1567890,
    totalDownVotes: 98765,
    rating: 94,
    creatorName: "Untitled Tag Studios",
    creatorType: "Group",
    genre: "All",
    thumbnailUrl: "https://tr.rbxcdn.com/180DAY-tag/768/432/Image/Webp",
    iconUrl: "https://tr.rbxcdn.com/180DAY-tag/150/150/Image/Webp",
    ageRecommendation: "All Ages",
    lastUpdated: new Date().toISOString(),
  },
  {
    rank: 19,
    universeId: 4059637689,
    placeId: 10739163425,
    name: "Combat Warriors",
    description: "Intense melee combat game with a variety of weapons!",
    playerCount: 43210,
    totalUpVotes: 1456789,
    totalDownVotes: 87654,
    rating: 94,
    creatorName: "SWAG Inc.",
    creatorType: "Group",
    genre: "Fighting",
    thumbnailUrl: "https://tr.rbxcdn.com/180DAY-cw/768/432/Image/Webp",
    iconUrl: "https://tr.rbxcdn.com/180DAY-cw/150/150/Image/Webp",
    ageRecommendation: "9+",
    lastUpdated: new Date().toISOString(),
  },
  {
    rank: 20,
    universeId: 3241608573,
    placeId: 8569011800,
    name: "Driving Empire",
    description: "Explore a vast open world and drive your dream cars!",
    playerCount: 32109,
    totalUpVotes: 1345678,
    totalDownVotes: 76543,
    rating: 95,
    creatorName: "Wayfort",
    creatorType: "Group",
    genre: "All",
    thumbnailUrl: "https://tr.rbxcdn.com/180DAY-de/768/432/Image/Webp",
    iconUrl: "https://tr.rbxcdn.com/180DAY-de/150/150/Image/Webp",
    ageRecommendation: "All Ages",
    lastUpdated: new Date().toISOString(),
  },
];

// Add more games to reach 50
export function generateMockGames(count: number = 50): LeaderboardGame[] {
  const additionalGames: Partial<LeaderboardGame>[] = [
    { name: "Royale High", genre: "Town and City", description: "Attend high school and explore magical realms!" },
    { name: "MeepCity", genre: "Town and City", description: "Make friends, play games, and customize your estate!" },
    { name: "Build A Boat For Treasure", genre: "All", description: "Build boats to reach treasure chests!" },
    { name: "Welcome to Bloxburg", genre: "Town and City", description: "Build houses and live your dream life!" },
    { name: "Super Golf", genre: "Sports", description: "Play mini golf with friends!" },
    { name: "Phantom Forces", genre: "Shooter", description: "FPS military shooter experience!" },
    { name: "Dungeon Quest", genre: "Adventure", description: "Explore dungeons and collect legendary gear!" },
    { name: "Islands", genre: "Survival", description: "Build and survive on your own island!" },
    { name: "Restaurant Tycoon 2", genre: "Tycoon", description: "Run your own restaurant empire!" },
    { name: "Theme Park Tycoon 2", genre: "Tycoon", description: "Build and manage your dream theme park!" },
    { name: "Speed Run 4", genre: "Obby", description: "Race through colorful dimensions!" },
    { name: "Epic Minigames", genre: "All", description: "Play 100+ different minigames!" },
    { name: "Flee the Facility", genre: "Horror", description: "Escape the beast or catch the survivors!" },
    { name: "Bad Business", genre: "Shooter", description: "Fast-paced FPS action!" },
    { name: "Tower Defense Simulator", genre: "Strategy", description: "Defend your base against waves of zombies!" },
    { name: "Sword Fight on the Heights", genre: "Fighting", description: "Classic sword fighting game!" },
    { name: "Super Hero Tycoon", genre: "Tycoon", description: "Build your own superhero base!" },
    { name: "RoBeats", genre: "All", description: "Rhythm game with great music!" },
    { name: "Dragon Ball Z: Final Stand", genre: "Fighting", description: "Train and battle in the DBZ universe!" },
    { name: "Lumber Tycoon 2", genre: "Tycoon", description: "Chop trees and build your lumber empire!" },
    { name: "Anime Dimensions", genre: "Adventure", description: "Fight through multiple anime universes!" },
    { name: "Counter Blox", genre: "Shooter", description: "Tactical FPS inspired by CS!" },
    { name: "Tower Heroes", genre: "Strategy", description: "Defend with powerful tower heroes!" },
    { name: "World // Zero", genre: "Adventure", description: "Explore dungeons in this anime RPG!" },
    { name: "Ragdoll Engine", genre: "All", description: "Physics sandbox with ragdolls!" },
    { name: "Nico's Nextbots", genre: "Horror", description: "Run from the nextbots!" },
    { name: "Deepwoken", genre: "Adventure", description: "Dark fantasy RPG with permadeath!" },
    { name: "A Bizarre Day", genre: "Fighting", description: "JoJo's Bizarre Adventure game!" },
    { name: "Your Bizarre Adventure", genre: "Fighting", description: "Another JoJo inspired fighting game!" },
    { name: "Funky Friday", genre: "All", description: "Rhythm game inspired by Friday Night Funkin!" },
  ];

  const allGames = [...mockGames];
  
  for (let i = 0; i < Math.min(additionalGames.length, count - mockGames.length); i++) {
    const baseGame = additionalGames[i];
    const rank = mockGames.length + i + 1;
    const playerCount = Math.floor(30000 - (rank * 500) + Math.random() * 5000);
    
    allGames.push({
      rank,
      universeId: 1000000000 + rank * 1000,
      placeId: 2000000000 + rank * 1000,
      name: baseGame.name || `Game ${rank}`,
      description: baseGame.description || "An exciting Roblox game!",
      playerCount: Math.max(1000, playerCount),
      totalUpVotes: Math.floor(1000000 + Math.random() * 2000000),
      totalDownVotes: Math.floor(50000 + Math.random() * 100000),
      rating: Math.floor(90 + Math.random() * 9),
      creatorName: `Studio ${rank}`,
      creatorType: Math.random() > 0.5 ? 'Group' : 'User',
      genre: baseGame.genre || 'All',
      thumbnailUrl: '',
      iconUrl: '',
      ageRecommendation: Math.random() > 0.5 ? 'All Ages' : '9+',
      lastUpdated: new Date().toISOString(),
    });
  }

  return allGames.slice(0, count);
}
